name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar dependencias
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install pytest flake8 coverage wordfreq

    - name: Revisar estilo de código
      run: |
        source venv/bin/activate
        flake8 ahorcado.py --max-line-length=100

    - name: Ejecutar tests
      run: |
        source venv/bin/activate
        pytest --maxfail=1 --disable-warnings --cov=ahorcado --cov-report=term-missing

    - name: Generar reporte de cobertura
      run: |
        source venv/bin/activate
        coverage xml
